version: 1.0.0

dev:
  keyvault-name: kv-devsecops-carlos
  resource-group: rg-devsecops-lab

uat:
  keyvault-name: kv-devsecops-uatt
  resource-group: rg-devsecops-uat

prd:
  keyvault-name: kv-devsecops-prdd
  resource-group: rg-devsecops-prd
